[package]
name = "mindmap"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.8", features = ["derive"] }
dotenv = "0.15.0"
futures = "0.3.30"
inquire = { version = "0.7.5", features = ["date"] }
langchain-rust = { version = "4.3.0", features = [
    "ollama",
    "ollama-rs",
    "postgres",
] }
serde_json = "1.0.118"
tokio = "1.38.0"
tokio-stream = "0.1.15"

[features]
default = ["ollama", "postgres"]
ollama = ["langchain-rust/ollama"]
postgres = ["langchain-rust/postgres"]

[profile.dev]
debug = "line-tables-only"
lto = "off"

[profile.ci]
inherits = "dev"
incremental = false

[profile.release]
debug = "line-tables-only"
lto = "fat"
codegen-units = 1

# Workaround: https://github.com/rust-lang/cargo/issues/12457 which causes
#             https://github.com/ipetkov/crane/issues/370
[profile.dev.build-override]
debug = false
[profile.ci.build-override]
debug = false
[profile.release.build-override]
debug = false
